// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatemain = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/example/create": {
            "post": {
                "tags": [
                    "category/example"
                ],
                "summary": "create",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/example.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful. click to expand response structure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/example/detail": {
            "post": {
                "tags": [
                    "category/example"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/example.DetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful. click to expand response structure",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/example.DetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/example/list": {
            "post": {
                "tags": [
                    "category/example"
                ],
                "summary": "list for data",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/example.ListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful. click to expand response structure",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.BaseDataList-example_ListItem"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/example/update": {
            "post": {
                "tags": [
                    "category/example"
                ],
                "summary": "update",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/example.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful. click to expand response structure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "example.CreateRequest": {
            "type": "object",
            "required": [
                "field1",
                "field2",
                "field3",
                "field4"
            ],
            "properties": {
                "field1": {
                    "description": "field1",
                    "type": "string",
                    "maxLength": 255
                },
                "field2": {
                    "description": "field2",
                    "type": "integer",
                    "maximum": 999999,
                    "minimum": 1
                },
                "field3": {
                    "description": "field3",
                    "type": "boolean"
                },
                "field4": {
                    "description": "field4, enums: 1 - A, 2 - B, 3 - C",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "example.DetailRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "record id",
                    "type": "integer"
                }
            }
        },
        "example.DetailResponse": {
            "type": "object",
            "required": [
                "create_time",
                "field1",
                "field2",
                "field3",
                "field4",
                "id",
                "update_time"
            ],
            "properties": {
                "create_time": {
                    "description": "create time",
                    "type": "integer"
                },
                "field1": {
                    "description": "field1",
                    "type": "string"
                },
                "field2": {
                    "description": "field2",
                    "type": "integer"
                },
                "field3": {
                    "description": "field3",
                    "type": "boolean"
                },
                "field4": {
                    "description": "field4, enums: 1 - A, 2 - B, 3 - C",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                },
                "id": {
                    "description": "record id",
                    "type": "integer"
                },
                "update_time": {
                    "description": "update time",
                    "type": "integer"
                }
            }
        },
        "example.ListItem": {
            "type": "object",
            "required": [
                "field1",
                "field2",
                "field3",
                "field4"
            ],
            "properties": {
                "field1": {
                    "description": "field1",
                    "type": "string"
                },
                "field2": {
                    "description": "field2",
                    "type": "integer"
                },
                "field3": {
                    "description": "field3",
                    "type": "boolean"
                },
                "field4": {
                    "description": "field4, enums: 1 - A, 2 - B, 3 - C",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "example.ListRequest": {
            "type": "object",
            "properties": {
                "field4": {
                    "description": "filter by field4, enums: 0 - All, 1 - A, 2 - B, 3 - C",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2,
                        3
                    ]
                },
                "page": {
                    "description": "page",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "size": {
                    "description": "number of items per page",
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 5
                }
            }
        },
        "example.UpdateRequest": {
            "type": "object",
            "required": [
                "field1",
                "field2",
                "field3",
                "field4",
                "id"
            ],
            "properties": {
                "field1": {
                    "description": "field1",
                    "type": "string",
                    "maxLength": 255
                },
                "field2": {
                    "description": "field2",
                    "type": "integer",
                    "maximum": 999999,
                    "minimum": 1
                },
                "field3": {
                    "description": "field3",
                    "type": "boolean"
                },
                "field4": {
                    "description": "field4, enums: 1 - A, 2 - B, 3 - C",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                },
                "id": {
                    "description": "record id",
                    "type": "integer"
                }
            }
        },
        "response.BaseDataList-example_ListItem": {
            "type": "object",
            "required": [
                "data",
                "page",
                "size",
                "total"
            ],
            "properties": {
                "data": {
                    "description": "data list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example.ListItem"
                    }
                },
                "page": {
                    "description": "page number",
                    "type": "integer"
                },
                "size": {
                    "description": "number of items per page",
                    "type": "integer"
                },
                "total": {
                    "description": "total count",
                    "type": "integer"
                }
            }
        },
        "response.Code": {
            "type": "integer",
            "enum": [
                0,
                9100001,
                9100002,
                9999999
            ],
            "x-enum-comments": {
                "InvalidParams": "invalid parameters",
                "NeedAuthorization": "need authorization",
                "Ok": "OK",
                "ServerInternalError": "internal server error"
            },
            "x-enum-varnames": [
                "Ok",
                "InvalidParams",
                "NeedAuthorization",
                "ServerInternalError"
            ]
        },
        "response.Response": {
            "type": "object",
            "required": [
                "code",
                "msg",
                "request_id"
            ],
            "properties": {
                "code": {
                    "description": "code, 0 if success, non-zero otherwise",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.Code"
                        }
                    ]
                },
                "data": {
                    "description": "data"
                },
                "msg": {
                    "description": "message, OK on success, error message otherwise",
                    "type": "string"
                },
                "request_id": {
                    "description": "request id, used for tracking",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfomain holds exported Swagger Info so clients can modify it
var SwaggerInfomain = &swag.Spec{
	Version:          "1.0",
	Host:             "example.com",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API Documents",
	Description:      "<div>\n<h2>特定状态码约定</h2>\n<table class=\"table\">\n<thead>\n<tr><th>code</th><th style=\"width: 100%\">description</th></tr>\n<thead>\n<tbody>\n<tr><td>1100001</td><td>Invalid Parameters</td></tr>\n<tr><td>9999999</td><td>Server Internal Error</td></tr>\n</tbody>\n</table>\n</div>",
	InfoInstanceName: "main",
	SwaggerTemplate:  docTemplatemain,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfomain.InstanceName(), SwaggerInfomain)
}
