debug = false

[logger]
level = "error"
outputs = ["stdout", "./logs/main.log"]
max_size = 100
max_age = 30
max_backups = 10

[database.mysql]
dsn = "user:password@tcp(127.0.0.1:3306)/database?charset=utf8mb4&loc=Local&multiStatements=true" # environment special config
conn_pool = { enable = true, max_idle_conn = 10, max_open_conn = 100, max_idle_life_time = 60 }

[cache]
prefix = ""

[server.http]
web = { listen = "8000", trusted_proxies = [], under_maintenance = false }
