// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	example2 "github.com/Luna-CY/Golang-Project-Template/internal/dao/example"
	example3 "github.com/Luna-CY/Golang-Project-Template/internal/service/example"
	"github.com/Luna-CY/Golang-Project-Template/server/http/gateway/web/handler/example"
)

// Injectors from wire.go:

func NewExample() *example.Example {
	exampleExample := example2.New()
	example4 := example3.New(exampleExample)
	example5 := example.New(example4)
	return example5
}
